<?php
/**
 * Redis
 *
 * @category Jdcloud
 * @package  Jdcloud\Redis
 * @author   Jdcloud <jdcloud-api@jd.com>
 * @license  Apache-2.0 http://www.apache.org/licenses/LICENSE-2.0
 * @link     https://www.jdcloud.com/help/faq
 */

namespace Jdcloud\Redis;

use Jdcloud\JdCloudClient;
use Jdcloud\Api\Service;
use Jdcloud\Api\DocModel;
use Jdcloud\Api\ApiProvider;
use Jdcloud\PresignUrlMiddleware;

/**
 * Client used to interact with redis.
 *
 * @method \Jdcloud\Result describeAvailableRegion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeAvailableRegionAsync(array $args = [])
 * @method \Jdcloud\Result describeAvailableResource(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeAvailableResourceAsync(array $args = [])
 * @method \Jdcloud\Result describeAvailableResource2(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeAvailableResource2Async(array $args = [])
 * @method \Jdcloud\Result describeCacheInstances(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeCacheInstancesAsync(array $args = [])
 * @method \Jdcloud\Result createCacheInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createCacheInstanceAsync(array $args = [])
 * @method \Jdcloud\Result recycledCacheInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise recycledCacheInstanceAsync(array $args = [])
 * @method \Jdcloud\Result deleteRecycledCacheInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteRecycledCacheInstanceAsync(array $args = [])
 * @method \Jdcloud\Result describeCacheInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeCacheInstanceAsync(array $args = [])
 * @method \Jdcloud\Result modifyCacheInstanceAttribute(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyCacheInstanceAttributeAsync(array $args = [])
 * @method \Jdcloud\Result deleteCacheInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteCacheInstanceAsync(array $args = [])
 * @method \Jdcloud\Result modifyCacheInstanceClass(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyCacheInstanceClassAsync(array $args = [])
 * @method \Jdcloud\Result describeResizeModeIpTimeInfo(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeResizeModeIpTimeInfoAsync(array $args = [])
 * @method \Jdcloud\Result resetCacheInstancePassword(array $args = [])
 * @method \GuzzleHttp\Promise\Promise resetCacheInstancePasswordAsync(array $args = [])
 * @method \Jdcloud\Result setExposeType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise setExposeTypeAsync(array $args = [])
 * @method \Jdcloud\Result describeInstanceConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeInstanceConfigAsync(array $args = [])
 * @method \Jdcloud\Result modifyInstanceConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyInstanceConfigAsync(array $args = [])
 * @method \Jdcloud\Result describeAnalysisTime(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeAnalysisTimeAsync(array $args = [])
 * @method \Jdcloud\Result modifyAnalysisTime(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyAnalysisTimeAsync(array $args = [])
 * @method \Jdcloud\Result describeCacheAnalysisList(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeCacheAnalysisListAsync(array $args = [])
 * @method \Jdcloud\Result createCacheAnalysis(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createCacheAnalysisAsync(array $args = [])
 * @method \Jdcloud\Result describeCacheAnalysisResult(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeCacheAnalysisResultAsync(array $args = [])
 * @method \Jdcloud\Result describeClientList(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeClientListAsync(array $args = [])
 * @method \Jdcloud\Result describeClientIpDetail(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeClientIpDetailAsync(array $args = [])
 * @method \Jdcloud\Result describeBackupInfo(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeBackupInfoAsync(array $args = [])
 * @method \Jdcloud\Result describeBackups(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeBackupsAsync(array $args = [])
 * @method \Jdcloud\Result createBackup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createBackupAsync(array $args = [])
 * @method \Jdcloud\Result describeBackupPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeBackupPolicyAsync(array $args = [])
 * @method \Jdcloud\Result modifyBackupPolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyBackupPolicyAsync(array $args = [])
 * @method \Jdcloud\Result describeInstanceTLS(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeInstanceTLSAsync(array $args = [])
 * @method \Jdcloud\Result modifyInstanceTLS(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyInstanceTLSAsync(array $args = [])
 * @method \Jdcloud\Result modifyPublicAddress(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyPublicAddressAsync(array $args = [])
 * @method \Jdcloud\Result describeUpgradeVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeUpgradeVersionAsync(array $args = [])
 * @method \Jdcloud\Result modifyInstanceMinorVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyInstanceMinorVersionAsync(array $args = [])
 * @method \Jdcloud\Result modifyInstanceNodeGroupVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyInstanceNodeGroupVersionAsync(array $args = [])
 * @method \Jdcloud\Result modifyInstanceVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyInstanceVersionAsync(array $args = [])
 * @method \Jdcloud\Result importData(array $args = [])
 * @method \GuzzleHttp\Promise\Promise importDataAsync(array $args = [])
 * @method \Jdcloud\Result haDiagnosis(array $args = [])
 * @method \GuzzleHttp\Promise\Promise haDiagnosisAsync(array $args = [])
 * @method \Jdcloud\Result describeAvailableSentinelList(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeAvailableSentinelListAsync(array $args = [])
 * @method \Jdcloud\Result describeSentinelAvailableZones(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeSentinelAvailableZonesAsync(array $args = [])
 * @method \Jdcloud\Result modifySentinel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifySentinelAsync(array $args = [])
 * @method \Jdcloud\Result modifySentinelAvailableZones(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifySentinelAvailableZonesAsync(array $args = [])
 * @method \Jdcloud\Result modifyRedisAZSpecifyType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyRedisAZSpecifyTypeAsync(array $args = [])
 * @method \Jdcloud\Result modifyInstanceType(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyInstanceTypeAsync(array $args = [])
 * @method \Jdcloud\Result modifyRedisAvailableZones(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyRedisAvailableZonesAsync(array $args = [])
 * @method \Jdcloud\Result modifyProxyAvailableZones(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyProxyAvailableZonesAsync(array $args = [])
 * @method \Jdcloud\Result switchInstanceHA(array $args = [])
 * @method \GuzzleHttp\Promise\Promise switchInstanceHAAsync(array $args = [])
 * @method \Jdcloud\Result restoreInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise restoreInstanceAsync(array $args = [])
 * @method \Jdcloud\Result describeDownloadUrl(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeDownloadUrlAsync(array $args = [])
 * @method \Jdcloud\Result describeClusterInfo(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeClusterInfoAsync(array $args = [])
 * @method \Jdcloud\Result describeIpWhiteList(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeIpWhiteListAsync(array $args = [])
 * @method \Jdcloud\Result modifyIpWhiteList(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyIpWhiteListAsync(array $args = [])
 * @method \Jdcloud\Result describeSlowLog(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeSlowLogAsync(array $args = [])
 * @method \Jdcloud\Result describeProxySlowLog(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeProxySlowLogAsync(array $args = [])
 * @method \Jdcloud\Result getMetric(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getMetricAsync(array $args = [])
 * @method \Jdcloud\Result describeTaskProgressList(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeTaskProgressListAsync(array $args = [])
 * @method \Jdcloud\Result getDisableCommands(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getDisableCommandsAsync(array $args = [])
 * @method \Jdcloud\Result setDisableCommands(array $args = [])
 * @method \GuzzleHttp\Promise\Promise setDisableCommandsAsync(array $args = [])
 * @method \Jdcloud\Result listDisableCommands(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listDisableCommandsAsync(array $args = [])
 * @method \Jdcloud\Result describeAccounts(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeAccountsAsync(array $args = [])
 * @method \Jdcloud\Result createAccount(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAccountAsync(array $args = [])
 * @method \Jdcloud\Result modifyAccount(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyAccountAsync(array $args = [])
 * @method \Jdcloud\Result deleteAccount(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteAccountAsync(array $args = [])
 * @method \Jdcloud\Result modifyAccounts(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyAccountsAsync(array $args = [])
 * @method \Jdcloud\Result startClearData(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startClearDataAsync(array $args = [])
 * @method \Jdcloud\Result stopClearData(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopClearDataAsync(array $args = [])
 * @method \Jdcloud\Result describeClearData(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeClearDataAsync(array $args = [])
 * @method \Jdcloud\Result describeDetailNodeList(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeDetailNodeListAsync(array $args = [])
 * @method \Jdcloud\Result describeBigKeyList(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeBigKeyListAsync(array $args = [])
 * @method \Jdcloud\Result createBigKeyAnalysis(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createBigKeyAnalysisAsync(array $args = [])
 * @method \Jdcloud\Result describeBigKeyDetail(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeBigKeyDetailAsync(array $args = [])
 * @method \Jdcloud\Result describeBigKeyAnalysisTime(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeBigKeyAnalysisTimeAsync(array $args = [])
 * @method \Jdcloud\Result modifyBigKeyAnalysisTime(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyBigKeyAnalysisTimeAsync(array $args = [])
 * @method \Jdcloud\Result stopCacheAnalysis(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopCacheAnalysisAsync(array $args = [])
 * @method \Jdcloud\Result describeAnalysisThreshold(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeAnalysisThresholdAsync(array $args = [])
 * @method \Jdcloud\Result modifyAnalysisThreshold(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyAnalysisThresholdAsync(array $args = [])
 * @method \Jdcloud\Result createBigKeyAnalysis2(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createBigKeyAnalysis2Async(array $args = [])
 * @method \Jdcloud\Result describeBigKeyList2(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeBigKeyList2Async(array $args = [])
 * @method \Jdcloud\Result describeBigKeyDetail2(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeBigKeyDetail2Async(array $args = [])
 * @method \Jdcloud\Result describeBigKeyAnalysisTime2(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeBigKeyAnalysisTime2Async(array $args = [])
 * @method \Jdcloud\Result modifyBigKeyAnalysisTime2(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyBigKeyAnalysisTime2Async(array $args = [])
 * @method \Jdcloud\Result describeAnalysisThreshold2(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeAnalysisThreshold2Async(array $args = [])
 * @method \Jdcloud\Result modifyAnalysisThreshold2(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyAnalysisThreshold2Async(array $args = [])
 * @method \Jdcloud\Result describeHotKeyResult2(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeHotKeyResult2Async(array $args = [])
 * @method \Jdcloud\Result describeHotKeyDetail2(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeHotKeyDetail2Async(array $args = [])
 * @method \Jdcloud\Result describeHotKeySummary(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeHotKeySummaryAsync(array $args = [])
 * @method \Jdcloud\Result describeHotKeyDetail(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeHotKeyDetailAsync(array $args = [])
 * @method \Jdcloud\Result restartProxy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise restartProxyAsync(array $args = [])
 * @method \Jdcloud\Result restartInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise restartInstanceAsync(array $args = [])
 * @method \Jdcloud\Result clientKill(array $args = [])
 * @method \GuzzleHttp\Promise\Promise clientKillAsync(array $args = [])
 * @method \Jdcloud\Result maintenanceTime(array $args = [])
 * @method \GuzzleHttp\Promise\Promise maintenanceTimeAsync(array $args = [])
 * @method \Jdcloud\Result modifyBlockStatus(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyBlockStatusAsync(array $args = [])
 * @method \Jdcloud\Result checkDeletable(array $args = [])
 * @method \GuzzleHttp\Promise\Promise checkDeletableAsync(array $args = [])
 * @method \Jdcloud\Result describeConfigModifyHistory(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeConfigModifyHistoryAsync(array $args = [])
 * @method \Jdcloud\Result recoverInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise recoverInstanceAsync(array $args = [])
 * @method \Jdcloud\Result listModules(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listModulesAsync(array $args = [])
 * @method \Jdcloud\Result loadModules(array $args = [])
 * @method \GuzzleHttp\Promise\Promise loadModulesAsync(array $args = [])
 * @method \Jdcloud\Result unloadModules(array $args = [])
 * @method \GuzzleHttp\Promise\Promise unloadModulesAsync(array $args = [])
 * @method \Jdcloud\Result jvesselV1Health(array $args = [])
 * @method \GuzzleHttp\Promise\Promise jvesselV1HealthAsync(array $args = [])
 * @method \Jdcloud\Result jvesselV1ProbeSuccessRate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise jvesselV1ProbeSuccessRateAsync(array $args = [])
 * @method \Jdcloud\Result jvesselV1ModifyProxyReplica(array $args = [])
 * @method \GuzzleHttp\Promise\Promise jvesselV1ModifyProxyReplicaAsync(array $args = [])
 * @method \Jdcloud\Result jvesselV1ModifyProxyFlavor(array $args = [])
 * @method \GuzzleHttp\Promise\Promise jvesselV1ModifyProxyFlavorAsync(array $args = [])
 * @method \Jdcloud\Result jvesselV1UpdateProxyImage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise jvesselV1UpdateProxyImageAsync(array $args = [])
 * @method \Jdcloud\Result jvesselV1RollingUpdate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise jvesselV1RollingUpdateAsync(array $args = [])
 * @method \Jdcloud\Result jvesselV1SetConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise jvesselV1SetConfigAsync(array $args = [])
 * @method \Jdcloud\Result jvesselV1ListMasterConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise jvesselV1ListMasterConfigAsync(array $args = [])
 * @method \Jdcloud\Result jvesselV1ListSlaveConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise jvesselV1ListSlaveConfigAsync(array $args = [])
 * @method \Jdcloud\Result jvesselV1ListProxyConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise jvesselV1ListProxyConfigAsync(array $args = [])
 * @method \Jdcloud\Result jvesselV1ProxyInfo(array $args = [])
 * @method \GuzzleHttp\Promise\Promise jvesselV1ProxyInfoAsync(array $args = [])
 * @method \Jdcloud\Result getBackupFiles(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getBackupFilesAsync(array $args = [])
 * @method \Jdcloud\Result createOfflineAnalysisTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createOfflineAnalysisTaskAsync(array $args = [])
 * @method \Jdcloud\Result listOfflineAnalysis(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listOfflineAnalysisAsync(array $args = [])
 * @method \Jdcloud\Result describeOfflineAnalysisOverview(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeOfflineAnalysisOverviewAsync(array $args = [])
 * @method \Jdcloud\Result describeOfflineAnalysisTopKeys(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeOfflineAnalysisTopKeysAsync(array $args = [])
 * @method \Jdcloud\Result describeOfflineAnalysisTopKeyPrefixList(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeOfflineAnalysisTopKeyPrefixListAsync(array $args = [])
 * @method \Jdcloud\Result describeOfflineAnalysisTime(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeOfflineAnalysisTimeAsync(array $args = [])
 * @method \Jdcloud\Result modifyOfflineAnalysisTime(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyOfflineAnalysisTimeAsync(array $args = [])
 * @method \Jdcloud\Result describeRedisServerLog(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeRedisServerLogAsync(array $args = [])
 * @method \Jdcloud\Result checkPasswordValid(array $args = [])
 * @method \GuzzleHttp\Promise\Promise checkPasswordValidAsync(array $args = [])
 * @method \Jdcloud\Result describeConfigTemplates(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeConfigTemplatesAsync(array $args = [])
 * @method \Jdcloud\Result createConfigTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createConfigTemplateAsync(array $args = [])
 * @method \Jdcloud\Result describeConfigTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeConfigTemplateAsync(array $args = [])
 * @method \Jdcloud\Result modifyTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyTemplateAsync(array $args = [])
 * @method \Jdcloud\Result deleteConfigTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteConfigTemplateAsync(array $args = [])
 * @method \Jdcloud\Result userDiagnoseInstances(array $args = [])
 * @method \GuzzleHttp\Promise\Promise userDiagnoseInstancesAsync(array $args = [])
 * @method \Jdcloud\Result listInstanceDiagnoseTasks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listInstanceDiagnoseTasksAsync(array $args = [])
 * @method \Jdcloud\Result listPinDiagnoseTasks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listPinDiagnoseTasksAsync(array $args = [])
 * @method \Jdcloud\Result userGetDiagnoseReport(array $args = [])
 * @method \GuzzleHttp\Promise\Promise userGetDiagnoseReportAsync(array $args = [])
 * @method \Jdcloud\Result queryDiagnosePolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise queryDiagnosePolicyAsync(array $args = [])
 * @method \Jdcloud\Result configDiagnosePolicy(array $args = [])
 * @method \GuzzleHttp\Promise\Promise configDiagnosePolicyAsync(array $args = [])
 * @method \Jdcloud\Result configOverrideMetric(array $args = [])
 * @method \GuzzleHttp\Promise\Promise configOverrideMetricAsync(array $args = [])
 * @method \Jdcloud\Result describeInstanceClass(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeInstanceClassAsync(array $args = [])
 * @method \Jdcloud\Result describeUserQuota(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeUserQuotaAsync(array $args = [])
 * @method \Jdcloud\Result describeImageReleases(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeImageReleasesAsync(array $args = [])
 * @method \Jdcloud\Result describeChartReleases(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeChartReleasesAsync(array $args = [])
 * @method \Jdcloud\Result describeSpecConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeSpecConfigAsync(array $args = [])
 * @method \Jdcloud\Result listTasks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTasksAsync(array $args = [])
 * @method \Jdcloud\Result listTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTaskAsync(array $args = [])
 * @method \Jdcloud\Result interruptTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise interruptTaskAsync(array $args = [])
 * @method \Jdcloud\Result modifyTaskRunTime(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyTaskRunTimeAsync(array $args = [])
 * @method \Jdcloud\Result cancelTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise cancelTaskAsync(array $args = [])
 * @method \Jdcloud\Result listTaskTypes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTaskTypesAsync(array $args = [])
 * @method \Jdcloud\Result describeWhiteListGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeWhiteListGroupAsync(array $args = [])
 * @method \Jdcloud\Result addWhiteListGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise addWhiteListGroupAsync(array $args = [])
 * @method \Jdcloud\Result modifyWhiteListGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyWhiteListGroupAsync(array $args = [])
 * @method \Jdcloud\Result deleteWhiteListGroup(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteWhiteListGroupAsync(array $args = [])
 */
class RedisClient extends JdCloudClient
{
    public function __construct(array $args)
    {
        $args['with_resolved'] = function (array $args) {
            $this->getHandlerList()->appendInit(
                PresignUrlMiddleware::wrap(
                    $this,
                    $args['endpoint_provider'],
                    [
                        'operations' => [
                        ],
                        'service' => 'redis',
                        'presign_param' => 'PresignedUrl',
                    ]
                ),
                'redis'
            );
        };

        parent::__construct($args);
    }
}