<?php
/**
 * Mps
 *
 * @category Jdcloud
 * @package  Jdcloud\Mps
 * @author   Jdcloud <jdcloud-api@jd.com>
 * @license  Apache-2.0 http://www.apache.org/licenses/LICENSE-2.0
 * @link     https://www.jdcloud.com/help/faq
 */

namespace Jdcloud\Mps;

use Jdcloud\JdCloudClient;
use Jdcloud\Api\Service;
use Jdcloud\Api\DocModel;
use Jdcloud\Api\ApiProvider;
use Jdcloud\PresignUrlMiddleware;

/**
 * Client used to interact with mps.
 *
 * @method \Jdcloud\Result createAiChatConv(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createAiChatConvAsync(array $args = [])
 * @method \Jdcloud\Result createRealtimeASRTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createRealtimeASRTaskAsync(array $args = [])
 * @method \Jdcloud\Result updateAsrTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateAsrTaskAsync(array $args = [])
 * @method \Jdcloud\Result accessRealtimeASRTaskToken(array $args = [])
 * @method \GuzzleHttp\Promise\Promise accessRealtimeASRTaskTokenAsync(array $args = [])
 * @method \Jdcloud\Result describeASRTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeASRTaskAsync(array $args = [])
 * @method \Jdcloud\Result deleteASRTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteASRTaskAsync(array $args = [])
 * @method \Jdcloud\Result describeASRTasks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeASRTasksAsync(array $args = [])
 * @method \Jdcloud\Result createNonRealtimeASRTasks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createNonRealtimeASRTasksAsync(array $args = [])
 * @method \Jdcloud\Result regenerateASRTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise regenerateASRTaskAsync(array $args = [])
 * @method \Jdcloud\Result importKnowledgeByASRTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise importKnowledgeByASRTaskAsync(array $args = [])
 * @method \Jdcloud\Result describeMyMinutesText(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeMyMinutesTextAsync(array $args = [])
 * @method \Jdcloud\Result saveMyMinutesText(array $args = [])
 * @method \GuzzleHttp\Promise\Promise saveMyMinutesTextAsync(array $args = [])
 * @method \Jdcloud\Result describeASRTaskContent(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeASRTaskContentAsync(array $args = [])
 * @method \Jdcloud\Result describeASRMinutesText(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeASRMinutesTextAsync(array $args = [])
 * @method \Jdcloud\Result saveASRMinutesText(array $args = [])
 * @method \GuzzleHttp\Promise\Promise saveASRMinutesTextAsync(array $args = [])
 * @method \Jdcloud\Result describeASRTaskTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeASRTaskTemplateAsync(array $args = [])
 * @method \Jdcloud\Result saveAsrTaskTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise saveAsrTaskTemplateAsync(array $args = [])
 * @method \Jdcloud\Result exportMinutesSummaryToWord(array $args = [])
 * @method \GuzzleHttp\Promise\Promise exportMinutesSummaryToWordAsync(array $args = [])
 * @method \Jdcloud\Result exportMinutesTextToWord(array $args = [])
 * @method \GuzzleHttp\Promise\Promise exportMinutesTextToWordAsync(array $args = [])
 * @method \Jdcloud\Result exportAsrContentToWord(array $args = [])
 * @method \GuzzleHttp\Promise\Promise exportAsrContentToWordAsync(array $args = [])
 * @method \Jdcloud\Result setCallbackSettings(array $args = [])
 * @method \GuzzleHttp\Promise\Promise setCallbackSettingsAsync(array $args = [])
 * @method \Jdcloud\Result queryCallbackSettings(array $args = [])
 * @method \GuzzleHttp\Promise\Promise queryCallbackSettingsAsync(array $args = [])
 * @method \Jdcloud\Result startProcessInstance(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startProcessInstanceAsync(array $args = [])
 * @method \Jdcloud\Result createGlobalHotWords(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createGlobalHotWordsAsync(array $args = [])
 * @method \Jdcloud\Result describeASRTaskHotWords(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeASRTaskHotWordsAsync(array $args = [])
 * @method \Jdcloud\Result createASRTaskHotWords(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createASRTaskHotWordsAsync(array $args = [])
 * @method \Jdcloud\Result updateASRTaskHotWords(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateASRTaskHotWordsAsync(array $args = [])
 * @method \Jdcloud\Result deleteASRTaskHotWords(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteASRTaskHotWordsAsync(array $args = [])
 * @method \Jdcloud\Result describeASRTaskHotWordsDetails(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeASRTaskHotWordsDetailsAsync(array $args = [])
 * @method \Jdcloud\Result updateASRTaskHotWordStatus(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateASRTaskHotWordStatusAsync(array $args = [])
 * @method \Jdcloud\Result submitImageDetectionTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise submitImageDetectionTaskAsync(array $args = [])
 * @method \Jdcloud\Result uploadFileToKnowledgeBase(array $args = [])
 * @method \GuzzleHttp\Promise\Promise uploadFileToKnowledgeBaseAsync(array $args = [])
 * @method \Jdcloud\Result batchUploadFileToKnowledgeBase(array $args = [])
 * @method \GuzzleHttp\Promise\Promise batchUploadFileToKnowledgeBaseAsync(array $args = [])
 * @method \Jdcloud\Result describeKnowledgeBaseFileDownloadUrl(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeKnowledgeBaseFileDownloadUrlAsync(array $args = [])
 * @method \Jdcloud\Result describeKnowledgeBaseFileRecords(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeKnowledgeBaseFileRecordsAsync(array $args = [])
 * @method \Jdcloud\Result updateKnowledgeBaseFileStatus(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateKnowledgeBaseFileStatusAsync(array $args = [])
 * @method \Jdcloud\Result deleteKnowledgeBaseFileRecord(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteKnowledgeBaseFileRecordAsync(array $args = [])
 * @method \Jdcloud\Result batchDeleteKnowledgeFileRecord(array $args = [])
 * @method \GuzzleHttp\Promise\Promise batchDeleteKnowledgeFileRecordAsync(array $args = [])
 * @method \Jdcloud\Result queryProcessDefinitionListPaging(array $args = [])
 * @method \GuzzleHttp\Promise\Promise queryProcessDefinitionListPagingAsync(array $args = [])
 * @method \Jdcloud\Result createProcessDefinition(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createProcessDefinitionAsync(array $args = [])
 * @method \Jdcloud\Result queryProcessDefinitionByCode(array $args = [])
 * @method \GuzzleHttp\Promise\Promise queryProcessDefinitionByCodeAsync(array $args = [])
 * @method \Jdcloud\Result deleteProcessDefinitionByCode(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteProcessDefinitionByCodeAsync(array $args = [])
 * @method \Jdcloud\Result queryProcessInstanceList(array $args = [])
 * @method \GuzzleHttp\Promise\Promise queryProcessInstanceListAsync(array $args = [])
 * @method \Jdcloud\Result queryProcessInstanceById(array $args = [])
 * @method \GuzzleHttp\Promise\Promise queryProcessInstanceByIdAsync(array $args = [])
 * @method \Jdcloud\Result deleteProcessInstanceById(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteProcessInstanceByIdAsync(array $args = [])
 * @method \Jdcloud\Result queryTaskListByProcessId(array $args = [])
 * @method \GuzzleHttp\Promise\Promise queryTaskListByProcessIdAsync(array $args = [])
 * @method \Jdcloud\Result submitSnapshotTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise submitSnapshotTaskAsync(array $args = [])
 * @method \Jdcloud\Result listSnapshotTasks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSnapshotTasksAsync(array $args = [])
 * @method \Jdcloud\Result getSnapshotTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSnapshotTaskAsync(array $args = [])
 * @method \Jdcloud\Result deleteSnapshotTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSnapshotTaskAsync(array $args = [])
 * @method \Jdcloud\Result querySnapshotTaskResult(array $args = [])
 * @method \GuzzleHttp\Promise\Promise querySnapshotTaskResultAsync(array $args = [])
 * @method \Jdcloud\Result listSnapshotTemplates(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listSnapshotTemplatesAsync(array $args = [])
 * @method \Jdcloud\Result createSnapshotTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createSnapshotTemplateAsync(array $args = [])
 * @method \Jdcloud\Result getSnapshotTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getSnapshotTemplateAsync(array $args = [])
 * @method \Jdcloud\Result modifySnapshotTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifySnapshotTemplateAsync(array $args = [])
 * @method \Jdcloud\Result deleteSnapshotTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteSnapshotTemplateAsync(array $args = [])
 * @method \Jdcloud\Result genTaskCodeList(array $args = [])
 * @method \GuzzleHttp\Promise\Promise genTaskCodeListAsync(array $args = [])
 * @method \Jdcloud\Result submitTranscodeJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise submitTranscodeJobAsync(array $args = [])
 * @method \Jdcloud\Result listTranscodeJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTranscodeJobsAsync(array $args = [])
 * @method \Jdcloud\Result getTranscodeJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getTranscodeJobAsync(array $args = [])
 * @method \Jdcloud\Result listTranscodeTemplates(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listTranscodeTemplatesAsync(array $args = [])
 * @method \Jdcloud\Result createTranscodeTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createTranscodeTemplateAsync(array $args = [])
 * @method \Jdcloud\Result getTranscodeTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getTranscodeTemplateAsync(array $args = [])
 * @method \Jdcloud\Result updateTranscodeTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateTranscodeTemplateAsync(array $args = [])
 * @method \Jdcloud\Result modifyTranscodeTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise modifyTranscodeTemplateAsync(array $args = [])
 * @method \Jdcloud\Result deleteTranscodeTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteTranscodeTemplateAsync(array $args = [])
 * @method \Jdcloud\Result createVeditJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createVeditJobAsync(array $args = [])
 * @method \Jdcloud\Result submitVeditJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise submitVeditJobAsync(array $args = [])
 * @method \Jdcloud\Result listVeditProjects(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listVeditProjectsAsync(array $args = [])
 * @method \Jdcloud\Result createVeditProject(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createVeditProjectAsync(array $args = [])
 * @method \Jdcloud\Result getVeditProject(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getVeditProjectAsync(array $args = [])
 * @method \Jdcloud\Result updateVeditProject(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateVeditProjectAsync(array $args = [])
 * @method \Jdcloud\Result deleteVeditProject(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteVeditProjectAsync(array $args = [])
 * @method \Jdcloud\Result describeVoiceprint(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeVoiceprintAsync(array $args = [])
 * @method \Jdcloud\Result saveVoiceprint(array $args = [])
 * @method \GuzzleHttp\Promise\Promise saveVoiceprintAsync(array $args = [])
 * @method \Jdcloud\Result deleteVoiceprint(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteVoiceprintAsync(array $args = [])
 * @method \Jdcloud\Result describeVoiceprints(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeVoiceprintsAsync(array $args = [])
 * @method \Jdcloud\Result listWatermarkTemplates(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listWatermarkTemplatesAsync(array $args = [])
 * @method \Jdcloud\Result createWatermarkTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createWatermarkTemplateAsync(array $args = [])
 * @method \Jdcloud\Result getWatermarkTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getWatermarkTemplateAsync(array $args = [])
 * @method \Jdcloud\Result updateWatermarkTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateWatermarkTemplateAsync(array $args = [])
 * @method \Jdcloud\Result deleteWatermarkTemplate(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteWatermarkTemplateAsync(array $args = [])
 * @method \Jdcloud\Result getStyleDelimiter(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getStyleDelimiterAsync(array $args = [])
 * @method \Jdcloud\Result setStyleDelimiter(array $args = [])
 * @method \GuzzleHttp\Promise\Promise setStyleDelimiterAsync(array $args = [])
 * @method \Jdcloud\Result deleteStyleDelimiter(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteStyleDelimiterAsync(array $args = [])
 * @method \Jdcloud\Result listImageStyle(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listImageStyleAsync(array $args = [])
 * @method \Jdcloud\Result createImageStyle(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createImageStyleAsync(array $args = [])
 * @method \Jdcloud\Result getImageStyle(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getImageStyleAsync(array $args = [])
 * @method \Jdcloud\Result updateImageStyle(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateImageStyleAsync(array $args = [])
 * @method \Jdcloud\Result deleteImageStyle(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteImageStyleAsync(array $args = [])
 * @method \Jdcloud\Result countImageStyle(array $args = [])
 * @method \GuzzleHttp\Promise\Promise countImageStyleAsync(array $args = [])
 * @method \Jdcloud\Result listThumbnailTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listThumbnailTaskAsync(array $args = [])
 * @method \Jdcloud\Result createThumbnailTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createThumbnailTaskAsync(array $args = [])
 * @method \Jdcloud\Result getThumbnailTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getThumbnailTaskAsync(array $args = [])
 * @method \Jdcloud\Result getNotification(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getNotificationAsync(array $args = [])
 * @method \Jdcloud\Result setNotification(array $args = [])
 * @method \GuzzleHttp\Promise\Promise setNotificationAsync(array $args = [])
 */
class MpsClient extends JdCloudClient
{
    public function __construct(array $args)
    {
        $args['with_resolved'] = function (array $args) {
            $this->getHandlerList()->appendInit(
                PresignUrlMiddleware::wrap(
                    $this,
                    $args['endpoint_provider'],
                    [
                        'operations' => [
                        ],
                        'service' => 'mps',
                        'presign_param' => 'PresignedUrl',
                    ]
                ),
                'mps'
            );
        };

        parent::__construct($args);
    }
}