<?php
/**
 * Jdaip
 *
 * @category Jdcloud
 * @package  Jdcloud\Jdaip
 * @author   Jdcloud <jdcloud-api@jd.com>
 * @license  Apache-2.0 http://www.apache.org/licenses/LICENSE-2.0
 * @link     https://www.jdcloud.com/help/faq
 */

namespace Jdcloud\Jdaip;

use Jdcloud\JdCloudClient;
use Jdcloud\Api\Service;
use Jdcloud\Api\DocModel;
use Jdcloud\Api\ApiProvider;
use Jdcloud\PresignUrlMiddleware;

/**
 * Client used to interact with jdaip.
 *
 * @method \Jdcloud\Result adminDescribeAccountMembers(array $args = [])
 * @method \GuzzleHttp\Promise\Promise adminDescribeAccountMembersAsync(array $args = [])
 * @method \Jdcloud\Result describeExperiments(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeExperimentsAsync(array $args = [])
 * @method \Jdcloud\Result createExperiment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createExperimentAsync(array $args = [])
 * @method \Jdcloud\Result describeExperiment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeExperimentAsync(array $args = [])
 * @method \Jdcloud\Result updateExperiment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateExperimentAsync(array $args = [])
 * @method \Jdcloud\Result deleteExperiment(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteExperimentAsync(array $args = [])
 * @method \Jdcloud\Result adminDescribeJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise adminDescribeJobsAsync(array $args = [])
 * @method \Jdcloud\Result adminDescribeJobsCount(array $args = [])
 * @method \GuzzleHttp\Promise\Promise adminDescribeJobsCountAsync(array $args = [])
 * @method \Jdcloud\Result adminDescribeJobList(array $args = [])
 * @method \GuzzleHttp\Promise\Promise adminDescribeJobListAsync(array $args = [])
 * @method \Jdcloud\Result describeJobTypes(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeJobTypesAsync(array $args = [])
 * @method \Jdcloud\Result describeJobs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeJobsAsync(array $args = [])
 * @method \Jdcloud\Result createJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createJobAsync(array $args = [])
 * @method \Jdcloud\Result describeJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeJobAsync(array $args = [])
 * @method \Jdcloud\Result updateJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateJobAsync(array $args = [])
 * @method \Jdcloud\Result deleteJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteJobAsync(array $args = [])
 * @method \Jdcloud\Result stopJob(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopJobAsync(array $args = [])
 * @method \Jdcloud\Result getJobEvents(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getJobEventsAsync(array $args = [])
 * @method \Jdcloud\Result getJobRestartHistory(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getJobRestartHistoryAsync(array $args = [])
 * @method \Jdcloud\Result getPodLogs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getPodLogsAsync(array $args = [])
 * @method \Jdcloud\Result describeInstances(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeInstancesAsync(array $args = [])
 * @method \Jdcloud\Result getInstanceEvents(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getInstanceEventsAsync(array $args = [])
 * @method \Jdcloud\Result adminDescribeRuns(array $args = [])
 * @method \GuzzleHttp\Promise\Promise adminDescribeRunsAsync(array $args = [])
 * @method \Jdcloud\Result adminDescribeRunsCount(array $args = [])
 * @method \GuzzleHttp\Promise\Promise adminDescribeRunsCountAsync(array $args = [])
 * @method \Jdcloud\Result adminDescribeRunList(array $args = [])
 * @method \GuzzleHttp\Promise\Promise adminDescribeRunListAsync(array $args = [])
 * @method \Jdcloud\Result describeRunConfigs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeRunConfigsAsync(array $args = [])
 * @method \Jdcloud\Result describeRuns(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeRunsAsync(array $args = [])
 * @method \Jdcloud\Result createRun(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createRunAsync(array $args = [])
 * @method \Jdcloud\Result deleteRun(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteRunAsync(array $args = [])
 * @method \Jdcloud\Result stopRun(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopRunAsync(array $args = [])
 * @method \Jdcloud\Result getRunEvents(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getRunEventsAsync(array $args = [])
 * @method \Jdcloud\Result getPodLogs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getPodLogsAsync(array $args = [])
 * @method \Jdcloud\Result describeDatasets(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeDatasetsAsync(array $args = [])
 * @method \Jdcloud\Result createDataset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createDatasetAsync(array $args = [])
 * @method \Jdcloud\Result describeDataset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeDatasetAsync(array $args = [])
 * @method \Jdcloud\Result updateDataset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateDatasetAsync(array $args = [])
 * @method \Jdcloud\Result deleteDataset(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteDatasetAsync(array $args = [])
 * @method \Jdcloud\Result describeDatasetVersions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeDatasetVersionsAsync(array $args = [])
 * @method \Jdcloud\Result describeDatasetVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeDatasetVersionAsync(array $args = [])
 * @method \Jdcloud\Result updateDatasetVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateDatasetVersionAsync(array $args = [])
 * @method \Jdcloud\Result deleteDatasetVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteDatasetVersionAsync(array $args = [])
 * @method \Jdcloud\Result adminDescribeDistillTasks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise adminDescribeDistillTasksAsync(array $args = [])
 * @method \Jdcloud\Result describeImages(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeImagesAsync(array $args = [])
 * @method \Jdcloud\Result createImage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createImageAsync(array $args = [])
 * @method \Jdcloud\Result describeImage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeImageAsync(array $args = [])
 * @method \Jdcloud\Result updateImage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateImageAsync(array $args = [])
 * @method \Jdcloud\Result deleteImage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteImageAsync(array $args = [])
 * @method \Jdcloud\Result getPodLogs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getPodLogsAsync(array $args = [])
 * @method \Jdcloud\Result describePublicImages(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describePublicImagesAsync(array $args = [])
 * @method \Jdcloud\Result rolloutInference(array $args = [])
 * @method \GuzzleHttp\Promise\Promise rolloutInferenceAsync(array $args = [])
 * @method \Jdcloud\Result pauseRollout(array $args = [])
 * @method \GuzzleHttp\Promise\Promise pauseRolloutAsync(array $args = [])
 * @method \Jdcloud\Result describeInferenceRollouts(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeInferenceRolloutsAsync(array $args = [])
 * @method \Jdcloud\Result describeInferences(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeInferencesAsync(array $args = [])
 * @method \Jdcloud\Result createInference(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createInferenceAsync(array $args = [])
 * @method \Jdcloud\Result describeInference(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeInferenceAsync(array $args = [])
 * @method \Jdcloud\Result updateInference(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateInferenceAsync(array $args = [])
 * @method \Jdcloud\Result deleteInference(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteInferenceAsync(array $args = [])
 * @method \Jdcloud\Result startInference(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startInferenceAsync(array $args = [])
 * @method \Jdcloud\Result stopInference(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopInferenceAsync(array $args = [])
 * @method \Jdcloud\Result describeInferenceEvents(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeInferenceEventsAsync(array $args = [])
 * @method \Jdcloud\Result describeServices(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeServicesAsync(array $args = [])
 * @method \Jdcloud\Result describeService(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeServiceAsync(array $args = [])
 * @method \Jdcloud\Result updateService(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateServiceAsync(array $args = [])
 * @method \Jdcloud\Result deleteService(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteServiceAsync(array $args = [])
 * @method \Jdcloud\Result updateServiceQPS(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateServiceQPSAsync(array $args = [])
 * @method \Jdcloud\Result describeInferencePods(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeInferencePodsAsync(array $args = [])
 * @method \Jdcloud\Result describeInferenceScale(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeInferenceScaleAsync(array $args = [])
 * @method \Jdcloud\Result createInferenceScale(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createInferenceScaleAsync(array $args = [])
 * @method \Jdcloud\Result updateInferenceScale(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateInferenceScaleAsync(array $args = [])
 * @method \Jdcloud\Result deleteInferenceScale(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteInferenceScaleAsync(array $args = [])
 * @method \Jdcloud\Result adminDescribeInferences(array $args = [])
 * @method \GuzzleHttp\Promise\Promise adminDescribeInferencesAsync(array $args = [])
 * @method \Jdcloud\Result adminDescribeInferenceCount(array $args = [])
 * @method \GuzzleHttp\Promise\Promise adminDescribeInferenceCountAsync(array $args = [])
 * @method \Jdcloud\Result describeNodeInstances(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeNodeInstancesAsync(array $args = [])
 * @method \Jdcloud\Result listMetrics(array $args = [])
 * @method \GuzzleHttp\Promise\Promise listMetricsAsync(array $args = [])
 * @method \Jdcloud\Result describePrivateModels(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describePrivateModelsAsync(array $args = [])
 * @method \Jdcloud\Result createModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createModelAsync(array $args = [])
 * @method \Jdcloud\Result updateModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateModelAsync(array $args = [])
 * @method \Jdcloud\Result deleteModel(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteModelAsync(array $args = [])
 * @method \Jdcloud\Result describeModelVersions(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeModelVersionsAsync(array $args = [])
 * @method \Jdcloud\Result describeModelVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeModelVersionAsync(array $args = [])
 * @method \Jdcloud\Result updateModelVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateModelVersionAsync(array $args = [])
 * @method \Jdcloud\Result deleteModelVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteModelVersionAsync(array $args = [])
 * @method \Jdcloud\Result describePublicModels(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describePublicModelsAsync(array $args = [])
 * @method \Jdcloud\Result describePublicModelVersion(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describePublicModelVersionAsync(array $args = [])
 * @method \Jdcloud\Result describeAdminPublicModels(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeAdminPublicModelsAsync(array $args = [])
 * @method \Jdcloud\Result describeNotebooks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeNotebooksAsync(array $args = [])
 * @method \Jdcloud\Result createNotebook(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createNotebookAsync(array $args = [])
 * @method \Jdcloud\Result describeNotebookCount(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeNotebookCountAsync(array $args = [])
 * @method \Jdcloud\Result describeNotebook(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeNotebookAsync(array $args = [])
 * @method \Jdcloud\Result updateNotebook(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateNotebookAsync(array $args = [])
 * @method \Jdcloud\Result deleteNotebook(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteNotebookAsync(array $args = [])
 * @method \Jdcloud\Result startNotebook(array $args = [])
 * @method \GuzzleHttp\Promise\Promise startNotebookAsync(array $args = [])
 * @method \Jdcloud\Result stopNotebook(array $args = [])
 * @method \GuzzleHttp\Promise\Promise stopNotebookAsync(array $args = [])
 * @method \Jdcloud\Result updateResourceProperties(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateResourcePropertiesAsync(array $args = [])
 * @method \Jdcloud\Result getNotebookEvents(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getNotebookEventsAsync(array $args = [])
 * @method \Jdcloud\Result getNotebookPods(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getNotebookPodsAsync(array $args = [])
 * @method \Jdcloud\Result saveImage(array $args = [])
 * @method \GuzzleHttp\Promise\Promise saveImageAsync(array $args = [])
 * @method \Jdcloud\Result describeImageTasks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeImageTasksAsync(array $args = [])
 * @method \Jdcloud\Result deleteImageTask(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteImageTaskAsync(array $args = [])
 * @method \Jdcloud\Result createNotebookLogCollectConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createNotebookLogCollectConfigAsync(array $args = [])
 * @method \Jdcloud\Result deleteNotebookLogCollectConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteNotebookLogCollectConfigAsync(array $args = [])
 * @method \Jdcloud\Result adminDescribeNotebooks(array $args = [])
 * @method \GuzzleHttp\Promise\Promise adminDescribeNotebooksAsync(array $args = [])
 * @method \Jdcloud\Result adminDescribeNotebookCount(array $args = [])
 * @method \GuzzleHttp\Promise\Promise adminDescribeNotebookCountAsync(array $args = [])
 * @method \Jdcloud\Result describeCodeRepoConfigs(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeCodeRepoConfigsAsync(array $args = [])
 * @method \Jdcloud\Result createCodeRepoConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createCodeRepoConfigAsync(array $args = [])
 * @method \Jdcloud\Result describeCodeRepoConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise describeCodeRepoConfigAsync(array $args = [])
 * @method \Jdcloud\Result updateCodeRepoConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateCodeRepoConfigAsync(array $args = [])
 * @method \Jdcloud\Result deleteCodeRepoConfig(array $args = [])
 * @method \GuzzleHttp\Promise\Promise deleteCodeRepoConfigAsync(array $args = [])
 * @method \Jdcloud\Result createWorkspace(array $args = [])
 * @method \GuzzleHttp\Promise\Promise createWorkspaceAsync(array $args = [])
 * @method \Jdcloud\Result updateWorkspace(array $args = [])
 * @method \GuzzleHttp\Promise\Promise updateWorkspaceAsync(array $args = [])
 * @method \Jdcloud\Result addQueues(array $args = [])
 * @method \GuzzleHttp\Promise\Promise addQueuesAsync(array $args = [])
 * @method \Jdcloud\Result removeQueues(array $args = [])
 * @method \GuzzleHttp\Promise\Promise removeQueuesAsync(array $args = [])
 */
class JdaipClient extends JdCloudClient
{
    public function __construct(array $args)
    {
        $args['with_resolved'] = function (array $args) {
            $this->getHandlerList()->appendInit(
                PresignUrlMiddleware::wrap(
                    $this,
                    $args['endpoint_provider'],
                    [
                        'operations' => [
                        ],
                        'service' => 'jdaip',
                        'presign_param' => 'PresignedUrl',
                    ]
                ),
                'jdaip'
            );
        };

        parent::__construct($args);
    }
}